{% set name = "rsconnect-python" %}
{% set version = "1.28.0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/rstudio/rsconnect-python/archive/refs/tags/{{ version }}.tar.gz
  sha256: 804f4c6d21177ecd4964c34ae03b4558ac0aac521f642d997fa4e61987fd584b

build:
  noarch: python
  entry_points:
    - rsconnect = rsconnect.main:cli
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - six >=1.14.0
    - click >=8.0.0
    - pip >=10.0.0  # rsconnect-python invokes pip as a subprocess
    - pyjwt >=2.4.0
    - semver >=2.0.0,<3.0.0
test:
  requires:
    - python {{ python_min }}
  imports:
    - rsconnect

about:
  home: https://github.com/rstudio/rsconnect-python
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: The rsconnect-python CLI and library

extra:
  recipe-maintainers:
    - amol-
    - aronatkins
    - edavidaja
    - tdstein
    - dbkegley
